import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useHomeSummary } from '@/features/dashboard';
import { useAuth } from '@/features/auth/useAuth';
import { useLanguage } from '@/i18n/LanguageProvider';
import { Button, Card, CardContent, CardHeader, CardTitle } from '@/components/ui';
import { ErrorState, Skeleton } from '@/components/shared/states';
import { ArrowRight, BarChart3, Boxes, CalendarDays, CheckCircle2, CircleAlert, ClipboardCheck, Clock3, MapPin, Sparkles, type LucideIcon } from 'lucide-react';

const monthNow = () => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`; };

function HomeMetric({ label, value, note, icon: Icon, className }: { label: string; value: string | number; note: string; icon: LucideIcon; className: string }) {
  return <Card className="border-border/70 shadow-sm"><CardContent className="flex items-start justify-between gap-3 p-5"><div><p className="text-sm font-medium text-muted-foreground">{label}</p><strong className="mt-2 block text-3xl tracking-tight">{value}</strong><p className="mt-1 text-xs text-muted-foreground">{note}</p></div><span className={`flex h-11 w-11 items-center justify-center rounded-2xl ${className}`}><Icon className="h-5 w-5" /></span></CardContent></Card>;
}

export function HomePage() {
  const { user, hasPermission } = useAuth();
  const { language, t } = useLanguage();
  const [month, setMonth] = useState(monthNow);
  const { data, isLoading, isError, error, refetch } = useHomeSummary(month);
  if (isLoading) return <div className="space-y-5"><Skeleton className="h-44 rounded-3xl" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-32 rounded-xl" />)}</div></div>;
  if (isError) return <ErrorState message={(error as Error)?.message} onRetry={refetch} />;

  const work = data?.data;
  const progress = Math.max(0, Math.min(100, work?.progress ?? 0));
  const firstName = user?.name?.split(' ')[0] || t('common.user');
  const monthLabel = new Intl.DateTimeFormat(language === 'id' ? 'id-ID' : 'en-US', { month: 'long', year: 'numeric' }).format(new Date(`${month}-01T00:00:00`));
  const frequencyLabel = (frequency: string) => t(`frequency.${frequency}`);

  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-3xl border border-primary/15 bg-gradient-to-br from-primary/15 via-card to-card p-6 shadow-sm sm:p-8"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-primary/10 blur-3xl" /><div className="relative flex flex-col gap-6 xl:flex-row xl:items-center xl:justify-between"><div className="max-w-2xl"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-primary"><Sparkles className="h-4 w-4" />{t('home.workspace')}</p><h1 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">{t('home.welcome', { name: firstName })}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground sm:text-base">{t('home.description')}</p></div><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><label className="text-xs font-medium text-muted-foreground">{t('common.period')}<input type="month" value={month} max={monthNow()} onChange={event => setMonth(event.target.value)} className="mt-1 block h-10 rounded-xl border bg-background px-3 text-sm text-foreground" /></label>{hasPermission('compliance.view') || hasPermission('compliance.execute') ? <Button asChild><Link to="/compliance"><ClipboardCheck className="mr-2 h-4 w-4" />{t('home.startChecklist')}</Link></Button> : null}</div></div></section>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><HomeMetric label={t('home.periodProgress')} value={`${progress}%`} note={monthLabel} icon={BarChart3} className="bg-primary/10 text-primary" /><HomeMetric label={t('home.myInventory')} value={work?.totalInventories ?? 0} note={t('home.myInventoryNote')} icon={Boxes} className="bg-sky-500/10 text-sky-600 dark:text-sky-400" /><HomeMetric label={t('home.pendingChecklist')} value={work?.pending ?? 0} note={t('home.affectedInventory', { count: work?.pendingItems.length ?? 0 })} icon={Clock3} className="bg-amber-500/10 text-amber-600 dark:text-amber-400" /><HomeMetric label={t('home.findings')} value={work?.findings ?? 0} note={(work?.findings ?? 0) ? t('home.followUp') : t('home.noFindings')} icon={CircleAlert} className={(work?.findings ?? 0) ? 'bg-red-500/10 text-red-600 dark:text-red-400' : 'bg-emerald-500/10 text-emerald-600'} /></div>

    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_340px]"><Card className="overflow-hidden"><CardHeader className="border-b bg-muted/20"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">{t('home.queue')}</p><CardTitle className="mt-1 text-lg">{t('home.priority')}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{t('home.outstandingAt', { period: monthLabel })}</p></div>{work?.pendingItems.length ? <span className="rounded-full bg-amber-500/10 px-3 py-1 text-xs font-semibold text-amber-700 dark:text-amber-300">{t('home.assets', { count: work.pendingItems.length })}</span> : null}</div></CardHeader><CardContent className="p-0">{!work?.pendingItems.length ? <div className="flex flex-col items-center px-6 py-16 text-center"><span className="mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-600"><CheckCircle2 className="h-7 w-7" /></span><h3 className="font-semibold">{t('home.allComplete')}</h3><p className="mt-1 text-sm text-muted-foreground">{t('home.noQueue')}</p></div> : <div className="divide-y">{work.pendingItems.map(item => <article key={item.id} className="flex flex-col gap-4 p-4 transition-colors hover:bg-muted/25 sm:flex-row sm:items-center"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><CalendarDays className="h-5 w-5" /></span><div className="min-w-0 flex-1"><h3 className="truncate font-semibold">{item.itemType}</h3><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="h-3.5 w-3.5" />{item.area}{item.specificArea ? ` / ${item.specificArea}` : ''}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{item.assetCode}</p></div><div className="flex items-center justify-between gap-4"><div className="text-right"><p className="text-sm font-semibold text-amber-600 dark:text-amber-400">{t('home.remaining', { count: item.remaining })}</p><p className="text-xs text-muted-foreground">{frequencyLabel(item.frequency)} · {item.firstPeriodLabel}</p></div><Button size="sm" asChild><Link to={`/inventory/${item.id}`}>{t('common.open')}<ArrowRight className="ml-1 h-4 w-4" /></Link></Button></div></article>)}</div>}</CardContent></Card>
      <div className="space-y-6"><Card><CardHeader><CardTitle className="text-base">{t('home.periodHealth')}</CardTitle></CardHeader><CardContent><div className="mx-auto flex h-44 w-44 items-center justify-center rounded-full" style={{ background: `conic-gradient(hsl(var(--primary)) ${progress * 3.6}deg, hsl(var(--muted)) 0deg)` }}><div className="flex h-32 w-32 flex-col items-center justify-center rounded-full bg-card"><strong className="text-3xl">{progress}%</strong><span className="text-xs text-muted-foreground">{t('home.complete')}</span></div></div><div className="mt-5 rounded-xl bg-muted/40 p-4 text-sm"><strong>{progress === 100 ? t('home.periodComplete') : progress >= 80 ? t('home.almostComplete') : t('home.needsAttention')}</strong><p className="mt-1 text-muted-foreground">{t('home.obligationsComplete', { completed: work?.completed ?? 0, total: work?.totalRequired ?? 0 })}</p></div></CardContent></Card>{hasPermission('dashboard.view') && <Button asChild variant="outline" className="w-full"><Link to="/dashboard"><BarChart3 className="mr-2 h-4 w-4" />{t('home.openAnalytics')}</Link></Button>}</div></div>
  </div>;
}
